### ISSUE TITLE
Интеграция перестала работать?

### ISSUE THREAD

**Issue by alexanderznamensky** [alryaz/hass-yandex-music-browser#17]
Есть ощущение, что Яндекс ужесточает использование своих сервисов.
Яндекс браузер - не исключение: у меня также перестали работать Yandex Maps, Yandex Transport.

У всех так? Это привет нам от Алексея Кудрина? )))

**Comment by ewGENIY16** [comment]
у меня тоже не работает

**Comment by IncognitoMSK** [comment]
+1

**Comment by juriozis** [comment]
+1

**Comment by DrunkHeron** [comment]
+1

**Comment by klugev303** [comment]
+1

**Comment by Zotio** [comment]
+1

**Comment by heibertelf** [comment]
Нужно подать запрос на удаление интеграции из HACS как нерабочей

**Comment by alryaz** [comment]
@heibertelf сам сейчас подам, действительно времени поддерживать сейчас нет.

**Comment by alryaz** [comment]
https://github.com/hacs/default/pull/2376

**Comment by alexanderznamensky** [comment]
Должен отметить, что все-таки интеграция работает. Нужно пару раз перезагрузить сервер и несколько раз войти в мультимедиа
