### ISSUE TITLE
Ошибка при обновлении на версию 0.3

### ISSUE THREAD

**Issue by vorlocsev** [alryaz/hass-yandex-music-browser#2]
интеграции.

Logger: custom_components.yandex_music_browser
Source: custom_components/yandex_music_browser/__init__.py:311
Integration: Браузер Яндекс Музыки (documentation, issues)
First occurred: 18:59:10 (2 occurrences)
Last logged: 18:59:59

No patches enabled, component will shut down

**Comment by alryaz** [comment]
> интеграции.
> 
> Logger: custom_components.yandex_music_browser
> Source: custom_components/yandex_music_browser/**init**.py:311
> Integration: Браузер Яндекс Музыки (documentation, issues)
> First occurred: 18:59:10 (2 occurrences)
> Last logged: 18:59:59
> 
> No patches enabled, component will shut down

Отключили мне интернет, не успел запушить v0.0.4

Там пофикшено
